### PR TITLE
Mapping between ons fields

### PR DESCRIPTION
**Pull request by ox-baloo**
Improving ouptut of county imd map script, which produces a map with the lsoa's of the county coloured by IMD and Sections on top.

Enabled adding of surrounding areas and colour their sections gray. This is not yet automatic to work out what the neighbouring districts are, but is a step towards it.
If section markers are added fits the initial opening of the map to this area
Added ability to choose whether to have a cluster marker layer or a marker layer

Please feel free to amend or discuss - my style is probably not amazing/has flaws

### CODE REVIEW

**Comment by AA-Turner** [comment]
Apart from those three all looks good - and I hope Ops went well!

**Comment by ox-baloo** [comment]
> 
> 
> In ScriptHandler, there's an option to load the ONS data when it has already been merged with the Census csv which I'm not sure I understand fully - would you be able to explain?

So the county_imd_map script is an example of this. Suppose that I want to create a map of the LSOAs in a Scout County coloured by thier IMD score. To do this the following steps are performed:
1. The Local authorities in which the County has Sections are identified
2. The LSOAs in these local authorities are identified

To identify the LSOAs in the local authorities you need to construct a map that takes the local authorities and gives you the LSOAs. If you just use the merged census data, then you only get the LSOAs that have a Section in them, therefore you need to use the whole postcode directory.
We could calculate these mappings and hold them statically, but it doesn't take too long to run, managing static data can be tricky - so would rather dynamically assess.

**Comment by AA-Turner** [comment]
@ox-baloo: Leaving the branch for you to delete in case you want to add anything else.

**Comment by AA-Turner** [comment]
> To identify the LSOAs in the local authorities you need to construct a map that takes the local authorities and gives you the LSOAs. If you just use the merged census data, then you only get the LSOAs that have a Section in them, therefore you need to use the whole postcode directory.
> We could calculate these mappings and hold them statically, but it doesn't take too long to run, managing static data can be tricky - so would rather dynamically assess.

Makes sense - thanks for pointing out. 

Is there a possible need for a standard way of loading datasets (e.g. ONS PD, age, Edubase) into the application? If so may raise as new issue, but what we have currently seems to work!

**Pull request merged**
