### PR TITLE
District boundaries

### PR DESCRIPTION
**Pull request by ox-baloo**
Added key_type to deal with the fact that I'm using D_ID as the key, which is an np.int32, whereas the others are categories I think?
Other changes in line with the fact that D_ID is an np.int32 (or at least numeric) rather than string unlike the other OS area columns

The long term plan for districts_buffered.geojson (which currently contains the calculated district boundaries for the South West is to have a static resource of all the District boundaries in the UK. However the South West took approx 6200s (1.5hrs) and I anticipate the UK taking a while given an increase in points by a factor of 12, and pretty sure the algorithm is non-linear (probably quadratic) - an interim could be to produce maps of the 10ish regions individually - the districts on the boundaries would be a little larger than they should be ...

### CODE REVIEW

**Comment by ox-baloo** [comment]
P.S. I intend to get better at writing slightly shorter commits to break it up a bit

**Comment by AA-Turner** [comment]
Also meant to ask this earlier - what does nu_XYZ mean? nu ie new, nu ie number, nu ie nearest udder :P ? 

I'm just confused - though lack of sleep could be responsible for that!

**Comment by AA-Turner** [comment]
I have a version of second_buffer_distance in testing that has reduced the first pass from 4550 seconds to 235.7 - a 19ish times improvement. As you said it's not running in O(n) time, and was running in a kind of quasi quadratic - it ran n * len(nearest_points) times - i.e. 13991 times with an average of about a third of a second per loop.

By removing the valid variable & moving return 0 to everywhere valid was set to false, this means that the loop can break early, saving quite a lot of time. This was possible as valid was only set to False, and initialised to True.

Working on further improvements and will report back. @ox-baloo: If you've a second, please could you explain the whole buffering thing again? You told me on the skype call a while ago but I have forgotten. if possible a flowchart/bulleted list of the process just to get my head around it would be really useful.

Thanks
-A

**Comment by AA-Turner** [comment]
@AA-Turner: For personal future reference: I was underestimating quatdratic time - 856t would be O(n), and O(n<sup>2</sup>) would be ~732750t - this is only 14000t or 50 times better than quadratic.

@AA-Turner:  Second note to self - get better at big o notation

**Comment by AA-Turner** [comment]
Down to 40 seconds for the whole SW England! - entire script time not just geometry stuff

**Comment by AA-Turner** [comment]
Full UK took 1670 seconds (27.5 mins), though I removed early breaking as I think I accidentally broke side-effects. For ref SW took 115 seconds under this change, so UK takes ~ 14x longer.

**Comment by ox-baloo** [comment]
> 
> 
> Also meant to ask this earlier - what does nu_XYZ mean? nu ie new, nu ie number, nu ie nearest udder :P ?
> 
> I'm just confused - though lack of sleep could be responsible for that!

Usually number

**Comment by ox-baloo** [comment]
> 
> 
> Down to 40 seconds for the whole SW England! - entire script time not just geometry stuff

Wow that's brilliant - to be honest when I finished working on it I was so pleased that it worked even though I knew it was incredibly inefficient ...

**Comment by ox-baloo** [comment]
> 
> 
> I have a version of second_buffer_distance in testing that has reduced the first pass from 4550 seconds to 235.7 - a 19ish times improvement. As you said it's not running in O(n) time, and was running in a kind of quasi quadratic - it ran n * len(nearest_points) times - i.e. 13991 times with an average of about a third of a second per loop.
> 
> By removing the valid variable & moving return 0 to everywhere valid was set to false, this means that the loop can break early, saving quite a lot of time. This was possible as valid was only set to False, and initialised to True.
> 
> Working on further improvements and will report back. @ox-baloo: If you've a second, please could you explain the whole buffering thing again? You told me on the skype call a while ago but I have forgotten. if possible a flowchart/bulleted list of the process just to get my head around it would be really useful.
> 
> Thanks
> -A

The objective is to draw as big circle as possible around each Section without encroaching on neighbouring districts.
Essentially the complications occur at the corners, or if you're in the middle - I'll see if I get chance for a flow chart - likely to be about 2 weeks though

**Comment by ox-baloo** [comment]
1. Find all the unique points from the Scout Census data
2. For each point, add the list of all the points that are within twice the distance of the closest point. This is because the maximum buffer distance is the distance to the nearest point.
3. For each point:
  i. If a buffer distance has already been set then do nothing
  ii. If a buffer distance has not been set then:
    a. Lookup the nearest points (i.e. points within twice the distance), for each of these
      i. if a buffer value has been set then if smaller, the buffer distance of this point is set to the complementary value to meet the other boundary
      ii. if a buffer value hasn't been set, then ignore if the point is too far away, else work out whether this point and the original point are a pair (i.e. mutually closest). Further invalidate the previous calculations if this point would affect them.
4. Got to 3 until no further buffer values can be set

**Comment by AA-Turner** [comment]
Thanks for the process list - really helpful!

RE district-boundaries, I'm still not sure that the datatype should be categorical - https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html - I think as each value in the names & codes file is unique we would be adding overhead.

Will look through the rest

**Comment by ox-baloo** [comment]
> 
> 
> Thanks for the process list - really helpful!
> 
> RE district-boundaries, I'm still not sure that the datatype should be categorical - https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html - I think as each value in the names & codes file is unique we would be adding overhead.
> 
> Will look through the rest

Okiedokie, to be honest not sure why I did that now, you should be able to create a local branch to track this one, make the changes, commit and push them - would you like to?

**Comment by AA-Turner** [comment]
> Okiedokie, to be honest not sure why I did that now, you should be able to create a local branch to track this one, make the changes, commit and push them - would you like to?

Will do!

**Comment by ox-baloo** [comment]
What do you think now? Did you make any changes to the algorithm?

**Comment by AA-Turner** [comment]
> What do you think now? Did you make any changes to the algorithm?

I do have changes that work, but I'm not happy yet with readability/performance - when I get to that point I'll push to a new branch. Happy with everything now - thanks for the updated everything & sorry for being awkward!

**Pull request merged**
